# fly.toml app configuration file generated for spring-surf-3476 on 2023-11-01T22:51:49+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "spring-surf-3476"
primary_region = "sin"

[mounts]
  source = "data"
  destination = "/data"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
